baseURL = "https://kqh.me/"
languageCode = "zh-HK"
title = "赫赫文王"
enableRobotsTXT = true
theme = "flex"
disablePathToLower = true
hasCJKLanguage = true
uglyURLs = false
rssLimit = 20
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[markup.tableOfContents]
        startLevel = 2
        endLevel = 3

# Enable author pages
[taxonomies]
author = "author"
tag = "tags"
category = "categories"
series = "series"
note = "notes"
subject = "subject"
auth = "auth"
from = "from"
toc = "toc"
book = "book"
step = "step"
[author]                  # essential
  name = "柯棋瀚"
[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
  [[menu.nav]]
     name = "HOME"
     weight = 1
     url = "/"
  [[menu.nav]]
         name = "works"
         weight =  2
         url = "/#gallery"
  [[menu.nav1]]
     name = "發現"
     weight = 3
     url = "/#discover"
     [[menu.nav1]]
        name = "歸檔"
        weight = 4
        url = "/post"
        [[menu.nav2]]
              name = "讀書"
              weight = 5
              url = "/read"
        [[menu.nav2]]
              name = "指北"
              weight = 6
              url = "/tutorial"
           [[menu.nav2]]
                 name = "資源"
                 weight = 7
                 url = "/recommend"
       [[menu.nav2]]
           name = "考試"
           weight = 8
           url = "/exam"
     [[menu.nav3]]
        name = "赫赫讚府"
        weight = 9
        url = "/zanfu"
        [[menu.nav3]]
               name = "春秋學刊"
               weight = 10
               url = "/xuekan"
    [[menu.nav3]]
         name = "琴譜文本"
         weight = 11
         url = "/qinpu"
         [[menu.nav3]]
            name = "文庫"
            weight = 12
            url = "/doc"
[params]
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">CC BY-NC-SA 4.0</a>，非商業用途可隨意使用'
  vertical = true
  width ="45rem"          # Any length in CSS syntax
  summaries= false      # Set to true to show summaries of posts on homepage
  divider= false        #\a0 Set to false to remove divider below posts on homepage
  schema= false         # Set to true to add Schema.org metadata
  opengraph= false      # Set to true to add Open Graph metadata
  twittercards= false   # Set to true to add Twitter Cards metadata
repository = "https://github.com/kujihhoe/HUGO-Theme-CJK/blob/master/content/"
