baseURL = "https://kqh.me/"
languageCode = "zh-HK"
title = "赫赫文王"
enableRobotsTXT = true
theme = "flex"
disablePathToLower = true
hasCJKLanguage = true
uglyURLs = false
rssLimit = 30
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[markup.tableOfContents]
        startLevel = 1
        endLevel = 3

# Enable author pages
[taxonomies]
author = "author"
tag = "tags"
category = "categories"
series = "series"
[author]                  # essential
  name = "柯棋瀚"
[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
  [[menu.nav]]
     name = "博客"
     weight = 1
     identifier = "archives"
     url = "/post"
   [[menu.nav]]
     name = "維基"
      weight = 7
    url = "https://kqh.wiki/"
[params]
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">CC BY-NC-SA 4.0</a>，非商業用途可隨意使用'
  linkToMarkDown = true
  vertical = true
  width ="45rem"          # Any length in CSS syntax
  summaries= false      # Set to true to show summaries of posts on homepage
  divider= false        #\a0 Set to false to remove divider below posts on homepage
  schema= false         # Set to true to add Schema.org metadata
  opengraph= false      # Set to true to add Open Graph metadata
  twittercards= false   # Set to true to add Twitter Cards metadata
  [[params.taxo]]
  name='史'
   des =  '都'
